apiVersion: v1
kind: Pod
metadata:
  name: arch
  namespace: default
spec:
  containers:
  - name: arch
    image: docker.io/archlinux:latest
    command:
      - sleep
      - "infinity"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always