apiVersion: v1
kind: Pod
metadata:
  name: arch
  namespace: default
spec:
  hostname: arch
  containers:
  - name: arch
    image: docker.io/archlinux:latest
    command:
      - sleep
      - "infinity"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - kb2
            - wsfd-netdev65.ntdv.lab.eng.bos.redhat.com
