apiVersion: v1
kind: Pod
metadata:
  name: arch
  namespace: default
spec:
  hostname: arch
  containers:
  - name: arch
    image: registry.homelab.vsq.cz/archlinux:latest
    command:
      - sleep
      - "infinity"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
  nodeSelector:
    "kubernetes.io/hostname": "kb2"
