apiVersion: v1
kind: Pod
metadata:
  name: netserver
  namespace: default
spec:
  hostname: netserver
  containers:
  - name: arch
    image: quay.io/networkstatic/netserver
    command:
      - netserver
      - "-D"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
  nodeSelector:
    "kubernetes.io/hostname": "kb3"