apiVersion: v1
kind: Pod
metadata:
  name: netserver
  namespace: default
spec:
  hostname: netserver
  containers:
  - name: arch
    image: quay.io/networkstatic/netserver
    command:
      - netserver
      - "-D"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - kb3
            - wsfd-netdev66.ntdv.lab.eng.bos.redhat.com
