apiVersion: v1
kind: Pod
metadata:
  name: victim
  namespace: default
spec:
  hostname: victim
  containers:
  - name: arch
    image: docker.io/archlinux:latest
    command:
      - sleep
      - "infinity"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
  nodeSelector:
    "kubernetes.io/hostname": "kb2"